import { useMemo, useState } from 'react'
import { BadgeCheck, FileText, RotateCcw, Save, X } from 'lucide-react'
import { GlassCard, StatusBadge } from '../../components/Ui'
import type { ClinicalContent } from '../../lib/content'
import type { AnswerRow, Competency, EvaluatorProfile, NurseRow, ReviewRow, SessionRow } from '../../lib/types'
import type { Lang } from '../../lib/i18n'
import { copy } from '../../lib/i18n'
import { percentLabel, scoreQuestions } from '../../lib/scoring'
import { supabase } from '../../lib/supabase'

type Props={lang:Lang;content:ClinicalContent;session:SessionRow;nurse:NurseRow;answers:AnswerRow[];reviews:ReviewRow[];evaluator:EvaluatorProfile|null;onClose:()=>void;onRefresh:()=>Promise<void>}
export function SessionPanel(p:Props){const t=copy[p.lang],rtl=p.lang==='ar';const [active,setActive]=useState(p.content.competencies[0]?.id||''),[comment,setComment]=useState(''),[staff,setStaff]=useState(''),[remedial,setRemedial]=useState(false),[date,setDate]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const c=p.content.competencies.find(x=>x.id===active) as Competency|undefined;const qs=useMemo(()=>p.content.questions.filter(q=>q.competency_id===active),[p.content,active]);const map=Object.fromEntries(p.answers.filter(a=>a.competency_id===active).map(a=>[a.question_id,a.answer]));const score=scoreQuestions(qs,map);const review=p.reviews.find(r=>r.competency_id===active)
function select(id:string){setActive(id);const r=p.reviews.find(x=>x.competency_id===id);setComment(r?.evaluator_comments||'');setStaff(r?.staff_comments||'');setRemedial(!!r?.needs_remedial);setDate(r?.remedial_date||'');setMsg('')}
async function save(finalize:boolean){if(finalize&&!p.evaluator){setMsg(rtl?'احفظ بيانات المقيم أولًا.':'Save the evaluator profile first.');return}setBusy(true);const {data,error}=await supabase.rpc('staff_save_review',{p_session:p.session.id,p_competency:active,p_evaluator_comments:comment||null,p_staff_comments:staff||null,p_needs_remedial:remedial,p_remedial_date:date||null,p_finalize:finalize});setBusy(false);const d=data as {ok?:boolean;error?:string}|null;if(error||!d?.ok)setMsg(error?.message||d?.error||'Error');else{setMsg(finalize?(rtl?'تم اعتماد الكفاءة.':'Competency finalized.'):(rtl?'تم الحفظ.':'Saved.'));await p.onRefresh()}}
async function status(action:'reopen'|'complete'){if(action==='complete'&&!p.evaluator){setMsg(rtl?'احفظ بيانات المقيم أولًا.':'Save evaluator profile first.');return}if(!confirm(action==='complete'?(rtl?'اعتماد الجلسة كاملة وإغلاقها؟':'Complete and lock the full session?'):(rtl?'إعادة فتح الجلسة للممرض؟':'Reopen this session?')))return;setBusy(true);const {data,error}=await supabase.rpc('staff_set_status',{p_session:p.session.id,p_action:action,p_reason:null});setBusy(false);const d=data as {ok?:boolean;error?:string}|null;if(error||!d?.ok)setMsg(error?.message||d?.error||'Error');else{await p.onRefresh();p.onClose()}}
return <div className="drawer-backdrop"><aside className="session-drawer"><div className="drawer-head"><div><h2>{p.nurse.name}</h2><small dir="ltr">{p.nurse.job_number}</small></div><button onClick={p.onClose}><X/></button></div><div className="drawer-actions"><StatusBadge status={p.session.status}/><button onClick={()=>window.open(`/print/${p.session.id}`,'_blank')}><FileText size={15}/>{t.print}</button>{p.session.status==='completed'?<button onClick={()=>void status('reopen')}><RotateCcw size={15}/>{t.reopen}</button>:<button className="primary" onClick={()=>void status('complete')}><BadgeCheck size={15}/>{t.complete}</button>}</div>{msg&&<div className="notice info">{msg}</div>}<div className="competency-tabs">{p.content.competencies.map(x=><button key={x.id} className={active===x.id?'active':''} onClick={()=>select(x.id)}>{x.code}</button>)}</div>{c&&<GlassCard className="review-card"><h3 dir="ltr">{c.title}</h3><div className="score-strip"><span>M <b>{score.m}</b></span><span>NM <b>{score.nm}</b></span><span>NA <b>{score.na}</b></span><span>% <b>{percentLabel(score.percent)}</b></span></div><div className="answer-list">{qs.map(q=><div key={q.id}><span dir="ltr">{q.number}. {q.text}</span><b className={`answer answer-${(map[q.id]||'none').toLowerCase()}`}>{map[q.id]||'—'}</b></div>)}</div><label>{t.comments}<textarea value={comment} onChange={e=>setComment(e.target.value)}/></label><label>{t.staffComments}<textarea value={staff} onChange={e=>setStaff(e.target.value)}/></label><div className="form-grid"><label className="check-label"><input type="checkbox" checked={remedial} onChange={e=>setRemedial(e.target.checked)}/>{t.remedial}</label><label>{t.remedialDate}<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><div className="row"><button onClick={()=>void save(false)} disabled={busy}><Save size={15}/>{t.save}</button><button className="primary" onClick={()=>void save(true)} disabled={busy||!!review?.finalized}><BadgeCheck size={15}/>{review?.finalized?t.completed:t.finalize}</button></div></GlassCard>}</aside></div>}
