import { useEffect, useState } from 'react'
import { Printer, X } from 'lucide-react'
import { loadClinicalContent, type ClinicalContent } from '../lib/content'
import { percentLabel, scoreQuestions } from '../lib/scoring'
import { supabase } from '../lib/supabase'
import type { AnswerRow, NurseRow, ReviewRow, SessionRow } from '../lib/types'

type Bundle={session:SessionRow;nurse:NurseRow;answers:AnswerRow[];reviews:ReviewRow[];signatureUrl:string|null}
export function PrintPage(){const id=location.pathname.split('/').filter(Boolean).pop()||'';const [content,setContent]=useState<ClinicalContent|null>(null),[bundle,setBundle]=useState<Bundle|null>(null),[error,setError]=useState('')
useEffect(()=>{void load()},[])
async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){setError('Evaluator sign-in required.');return}const {data:p}=await supabase.from('profiles').select('role').eq('id',user.id).single();if(!p||!['manager','admin'].includes(p.role)){setError('Evaluator access required.');return}const c=await loadClinicalContent();setContent(c);const [s,n,a,r]=await Promise.all([supabase.from('assessment_sessions').select('*').eq('id',id).single(),supabase.from('nurses').select('*'),supabase.from('assessment_answers').select('*').eq('session_id',id),supabase.from('manager_reviews').select('*').eq('session_id',id)]);if(s.error||a.error||r.error){setError(s.error?.message||a.error?.message||r.error?.message||'Unable to load form.');return}const session=s.data as SessionRow;const nurse=(n.data||[]).find((x:any)=>x.id===session.nurse_id) as NurseRow|undefined;if(!nurse){setError('Nurse record not found.');return}const reviews=(r.data||[]) as ReviewRow[];const snap=reviews.find(x=>x.evaluator_snapshot)?.evaluator_snapshot as Record<string,any>|undefined;let signatureUrl:null|string=null;if(snap?.signature_path){const signed=await supabase.storage.from('signatures').createSignedUrl(String(snap.signature_path),300);signatureUrl=signed.data?.signedUrl||null}setBundle({session,nurse,answers:(a.data||[]) as AnswerRow[],reviews,signatureUrl})}
if(error)return <div className="print-error">{error}</div>;if(!content||!bundle)return <div className="print-error">Loading…</div>
return <div className="print-app"><div className="print-toolbar"><button onClick={()=>window.print()}><Printer size={16}/>Print / Save PDF</button><button onClick={()=>window.close()}><X size={16}/>Close</button></div><div className="paper-stack">{content.competencies.map(c=>{const qs=content.questions.filter(q=>q.competency_id===c.id);const map=Object.fromEntries(bundle.answers.filter(a=>a.competency_id===c.id).map(a=>[a.question_id,a.answer]));const score=scoreQuestions(qs,map);const review=bundle.reviews.find(r=>r.competency_id===c.id);const snap=(review?.evaluator_snapshot||{}) as Record<string,any>;return <article className="official-paper" key={c.id}>
<header className="paper-head"><div><strong>AL HADETHA GENERAL HOSPITAL</strong><span>NURSING SERVICE DEPARTMENT</span></div><div className="paper-code">SPECIFIC COMPETENCY</div></header>
<h1>{c.title}</h1><div className="paper-fields"><span>Name: <b className="handwriting">{bundle.nurse.name}</b></span><span>Job Number: <b className="handwriting">{bundle.nurse.job_number}</b></span><span>Unit: <b>{bundle.nurse.unit||''}</b></span><span>Job Title: <b>{bundle.nurse.job_title||''}</b></span></div>
<div className="rating-key">M = Met &nbsp;&nbsp; NM = Not Met &nbsp;&nbsp; NA = Not Applicable</div>
<table><thead><tr><th>#</th><th>Competency Statement</th><th>M</th><th>NM</th><th>NA</th></tr></thead><tbody>{content.sections.filter(s=>s.competency_id===c.id).map(sec=><FragmentRows key={sec.id} title={`${sec.numeral}. ${sec.title}`} questions={qs.filter(q=>q.section_id===sec.id)} map={map}/>)}</tbody></table>
<div className="paper-score"><span>Raw Score: <b>{score.m}</b></span><span>Total Score: <b>{score.totalApplicable}</b></span><span>Rating: <b>{percentLabel(score.percent)}</b></span><span>Needs Remedial: <b>{review?.needs_remedial?'YES':'NO'}</b></span></div>
<div className="paper-comments"><div><b>Evaluator's Comments / Recommendations</b><p>{review?.evaluator_comments||''}</p></div><div><b>Staff Nurse Comments</b><p>{review?.staff_comments||''}</p></div></div>
<div className="paper-sign"><div><b>Evaluated By</b><p>Evaluator's Name: <span className="handwriting">{snap.name||''}</span></p><p>Job Number: <span className="handwriting">{snap.job_number||''}</span></p>{bundle.signatureUrl&&<img src={bundle.signatureUrl} alt="Evaluator signature"/>}</div><div><b>Confirmed By</b><p>Staff Name: <span className="handwriting">{bundle.nurse.name}</span></p><p>Date: {review?.finalized_at?new Date(review.finalized_at).toLocaleDateString('en-GB'):''}</p></div></div>
<footer>Generated from Nursing Competency · Powered by HALRWEOLI</footer></article>})}</div></div>}

function FragmentRows({title,questions,map}:{title:string;questions:any[];map:Record<string,string>}){return <><tr className="section-row"><td colSpan={5}>{title}</td></tr>{questions.map(q=><tr key={q.id}><td>{q.number}</td><td>{q.text}{q.needs_source_review&&<small className="source-mark"> NEEDS SOURCE REVIEW</small>}</td>{['M','NM','NA'].map(r=><td key={r} className="check-cell">{map[q.id]===r?<span className="paper-check">✓</span>:''}</td>)}</tr>)}</>}
