import { BadgeCheck, ClipboardCheck } from 'lucide-react'
import { GlassCard, Metric } from '../../components/Ui'
import type { ClinicalContent } from '../../lib/content'
import type { Competency, Rating } from '../../lib/types'
import type { Lang } from '../../lib/i18n'
import { copy } from '../../lib/i18n'
import { percentLabel, scoreQuestions } from '../../lib/scoring'

type Props={lang:Lang;content:ClinicalContent;answers:Record<string,Rating>;busy:boolean;onBack:()=>void;onOpen:(c:Competency,q?:string)=>void;onSubmit:()=>void}
export function ReviewView(p:Props){const t=copy[p.lang],rtl=p.lang==='ar',missing=p.content.questions.filter(q=>!p.answers[q.id]);const vals=Object.values(p.answers);return <div className="question-wrap"><GlassCard><div className="eyebrow"><ClipboardCheck size={15}/>{t.reviewTitle}</div><h1>{rtl?'راجع إجاباتك قبل الإرسال':'Review before submission'}</h1><div className="metrics"><Metric value={`${vals.length}/${p.content.questions.length}`} label={t.progress}/><Metric value={vals.filter(x=>x==='M').length} label="M — Met"/><Metric value={vals.filter(x=>x==='NM').length} label="NM — Not Met"/><Metric value={vals.filter(x=>x==='NA').length} label="NA — Not Applicable"/></div><div className={`notice ${missing.length?'warning':'success'}`}>{missing.length?`${t.unanswered}: ${missing.length}`:(rtl?'جميع العبارات تم تقييمها.':'Every competency statement has a response.')}</div><div className="review-list">{p.content.competencies.map(c=>{const qs=p.content.questions.filter(q=>q.competency_id===c.id);const s=scoreQuestions(qs,p.answers);const m=qs.find(q=>!p.answers[q.id]);return <button key={c.id} className={m?'missing':''} onClick={()=>p.onOpen(c,m?.id)}><span>{c.sort_order}</span><span><b dir="ltr">{c.title}</b><small>{s.answered}/{qs.length}</small></span><strong>{s.result==='Incomplete'?'—':percentLabel(s.percent)}</strong></button>})}</div><div className="question-nav"><button onClick={p.onBack}>{t.back}</button><button className="primary" disabled={!!missing.length||p.busy} onClick={p.onSubmit}><BadgeCheck size={16}/>{p.busy?'…':t.submit}</button></div></GlassCard></div>}
