# Verbatim transcription of the scanned "Long stay Department - SPECIFIC COMPETENCY" forms.
# Text (including original spelling and numbering) is copied exactly as printed on the source scans.
# Items are (label, text); label is the number printed in the first column.

def seq(*texts):
    return [(f"{i + 1}.", t) for i, t in enumerate(texts)]

FORMS = [
    {
        "slug": "specific-end-of-life-care",
        "title": "END OF LIFE CARE",
        "knowledge": seq(
            "States the nurse's role in the care of the dying patient.",
            "Verbalizes psychological needs of the dying patient and family of the dying patient.",
            "Verbalizes physical needs of the dying patient.",
            "States signs and symptoms of discomfort in the dying patient and nursing interventions for each.",
            "Verbalizes spiritual needs of the dying patient and patient's family.",
            "States the nurse's role in ensuring adequate pain management for the dying patient",
            "Verbalizes support required by patient's family after death and throughout the grief process",
        ),
        "skills": seq(
            "Demonstrates nursing care of the dying patient.",
            "Demonstrates assessment of pain and preparation and administration of drugs to relieve pain.",
            "Demonstrates nursing interventions to relieve symptoms of discomfort experienced by the dying patient.",
            "Demonstrates support for patient and family psychological, social and spiritual needs.",
            "Documents assessments, interventions and care of the dying patient.",
            "Provides and documents teaching given to family members and ensures for grief counselling when appropriate.",
        ),
        "attitude": seq(
            "Provides respectful and responsive care to the dying patient by providing comfort and dignity.",
            "Provides respect for the following needs confidentiality, Privacy Security, resolutions of complains, Pastoral counselling (No Pastoral services are available in Saudi Arabia, for religious contact embassy) and Communication.",
        ),
    },
    {
        "slug": "specific-basic-cardiac-monitoring",
        "title": "BASIC CARDIAC MONITORING",
        "knowledge": seq(
            "Discuss the correct placement of the electrodes required for BASIC CARDIAC MONITORING e.g. Red, Yellow and Green/Black.",
            "State the landmarks for the electrodes e.g. Green/Black at mid axilla which is between the 4^th and 5^th intercostal space below the nipple.",
            "Discuss how to correctly prepare the skin for the electrode application e.g. wipe the skin with alcohol swabs and dry, shave the hair from the area and clean with alcohol swabs and dry.",
            "Discuss the rationale for taking a baseline printed strip of the cardiac rhythm and why it is important to compare this baseline strip with any previous strips or ECG reading/s.",
            "Explore the reasons that would necessitate calling the Physician to examine the patient due to a rhythm change e.g. explain the normal PQRST complex.",
            "Explain how to document BASIC CARDIAC MONITORING findings correctly.",
        ),
        "skills": seq(
            "Demonstrate the correct placement of the electrodes required for BASIC CARDIAC MONITORING e.g. Red, Yellow and Green/Black.",
            "Show how to find the landmarks for the electrodes e.g. Green/Black at mid axilla which is between the 4^th and 5^th intercostal space below the nipple.",
            "Demonstrate how to correctly prepare the skin for the electrode application e.g. wipe the skin with alcohol swabs and dry, shave the hair from the area and clean with alcohol swabs and dry.",
            "Show how to take a baseline printed strip of the cardiac rhythm and how to compare this baseline strip with any previous strips or ECG reading/s.",
            "Demonstrate what the components of the by drawing a normal PQRST complex.",
        ),
        "attitude": seq(
            "Accept constrictive criticism as learning opportunity.",
            "To be self-aware of limitation in knowledge and skills.",
            "To be approachable and open to answer patients and family's questions.",
            "Attentive to overall patient experience e.g. pain, anxiety and have ability to provide comfort and emotional support as needed.",
            "Ability to organize and facilitate a Reflection session in and on practice after a BASIC CARDIAC MONITORING learning opportunity occurs and activates findings to improve future practice and response.",
        ),
    },
    {
        "slug": "specific-enteral-feeding",
        "title": "ENTERAL FEEDING",
        "knowledge": seq(
            "States nurse's responsibilities in caring for a patient receiving enteral feed.",
            "Verbalizes assessment required before , during and after feeding",
            "Discusses the risks and complications related to enteral feeding",
            "States nursing interventions and responsibilities in reducing risks associated with enteral feeding",
        ),
        "skills": seq(
            "Demonstrates safe enteral feeding technique with tubes placed in the stomach , duodenum and jejunum",
            "Demonstrates care for a patient with an enteral feeding tube including NGT , gastrostomy and/or jejunostomy tube.",
            "Performs proper documentation of assessment, interventions and care of the patient with an enteral feeding tube.",
            "Provides and documents teaching to patient/family about enteral feeding",
        ),
        "attitude": seq(
            "Provides respect and maintain dignity and privacy while handling the patient.",
        ),
    },
    {
        "slug": "specific-diabetes-melitus-education",
        "title": "DIABETES MELITUS EDUCATION",
        "knowledge": seq(
            "States the role and responsibilities of the nurse as a Diabetic Educator to include steps in assessing a patient's/patient's care provider readiness to learn, and the barriers to learning.",
            "Discusses the treatment options for DM type 1 and Type II and care required for the patient/ family / care provider.",
            "Examines the role of the nurse in supporting the patient with DM for self, home care, and healthy adaptation to DM.",
            "Discuss the signs and symptoms of hypoglycemia and hyperglycemia with particular emphasis on interventions appropriate for patients demonstrating signs and symptoms of complications.",
            "Formulate patient centered goals to reduce potential complications for patients with DM.",
            "Verbalizes psychological/psychosocial/ school needs of patients with DM, identifying resources available for patient teaching with GGH Hospital.",
            "Discuss factors influencing blood sugar levels (age specific) and the relevance of HbA1c monitoring.",
            "Discuss the different types of insulin with emphasis on rationale, onset, peak action, duration; care and various treatment options.",
            "States the nurse's responsibility associated with initiating and conducting group teaching sessions with particular emphasis on diabetic prevention, lifestyle changes, including exercise regimes.",
        ),
        "skills": seq(
            "Demonstrates patient / family / care provider point-of-care glucose assessment and how to order HbA1c.",
            "Demonstrates patient / family / care provider  teaching, preparation and administration of insulin therapy.",
            "Demonstrates how to teach people about hypoglycemia or hyperglycemia and corrective measure for home care.",
            "Demonstrates teaching for reduction of complication of DM, health promotion, for the patient with DM in suitable learning environment.",
            "Demonstrates how to document teaching to patient / family / care provider regarding DM in the Patient Teaching Record.",
            "Provides culturally sensitive teaching to patient / family / care provider regarding DM using appropriate educational materials.",
            "Provides strategies to modify and adjust the teaching for the child and adolescent with DM according to the stage of growth and development.",
            "Demonstrates ability to write program goals and objectives, organize Health Campaigns and collect and record data as well as analyze it.",
        ),
        "attitude": seq(
            "Provides respect and maintain dignity and privacy while handling the patient / family.",
        ),
    },
    {
        "slug": "specific-ambulance-transport",
        "title": "AMBULANCE TRANSPORT",
        "knowledge": seq(
            "Discuss the different levels of TRANSPORT applicable to area of practice.",
            "Verbalize the role and responsibilities of the nurse and driver during the AMBULANCE TRANSFER.",
            "Discuss the policy for checking the AMBULANCE and the equipment required to meet specific individual patient needs e.g. Emergency Transport Bag.",
            "Explain how to prepare the AMBULANCE according to patient needs e.g. compartment temperature needs to be low for blood transfusions.",
            "Discuss rationale for having any back-up switches for alternative power sources should the normal ones fail for any reason e.g. electrical power.",
            "Explain the importance of seatbelts and what to do if emergency care needs to be given and the seatbelt prevents this.",
            "Explain rational for knowing the level of oxygen PsI needed for each TRANSPORT.",
            "Discuss the rationale for having the TRANSFER Acceptance Form and the need for the Shift Supervisor/Designee to give the official “go ahead” to leave.",
            "Explain reporting process for diverting or stopping an AMBULANCE during a trip.",
            "Discuss the documentation needed for an AMBULANCE TRANSPORT for area of practice.",
        ),
        "skills": seq(
            "Demonstrate checking the AMBULANCE and the equipment required to meet specific individual patient needs e.g. Emergency Transport Bag.",
            "Demonstrate loading and unloading AMBULANCE stretcher or isolate depending on area of practice.",
            "Demonstrate use of AMBULANCE equipment and any standby switches for alternative power sources.",
            "Demonstrate use of AMBULANCE communication equipment as appropriate.",
            "Demonstrate how to check oxygen cylinders including the spare ones.",
            "Demonstrate the reporting process for diverting or stopping an AMBULANCE during a trip.",
            "Complete the documentation needed for an AMBULANCE TRANSPORT for area of practice.",
        ),
        "attitude": seq(
            "To be calm and able to think critically and creatively with limited resources as required tocare for the patient during the AMBULANCE TRANSPORT.",
            "To be self-aware of limitation in knowledge and skills.",
            "Ability of nurse to respond professionally and calmly if patient should deteriorate during the TRANSFER.",
            "Ability to communicate with EMS/ER physician and Shift Supervisor/Designee and respond to instruction as relevant and appropriate.",
            "Demonstrate ability to organize and facilitate a Reflection Session in and on practice should an unexpected situation occur during an AMBULANCE TRANSFER and activate findings to improve future practice and response.",
            "To be approachable and open to answer patient and family's questions.",
        ),
        "italic_attitude": [0, 1, 5],
    },
    {
        "slug": "specific-tracheostomy",
        "title": "TRACHEOSTOMY",
        "knowledge": seq(
            "Discusses the indications for tracheostomy.",
            "Discusses the complication of tracheostomy.",
            "Discusses the technique to replace misplaced tracheostomy tube.",
            "Verbalizes the impact of the tracheostomy on the patient / family.",
            "States the nurse's responsibilities with regard to caring for a patient with a tracheostomy.",
        ),
        "skills": seq(
            "Demonstrates skills with the care of the tracheostomy and surrounding.",
            "Demonstrates assessment and technical skills regarding the need for and provision of suction to the tracheostomy.",
            "Demonstrates safety awareness when caring for a patient with a tracheostomy.",
            "Documents related assessment/intervention and care of a patient with a tracheostomy.",
        ),
        "attitude": seq(
            "Provides age-specific and culturally sensitive patient teaching to patient and family.",
        ),
    },
    {
        "slug": "specific-infection-control",
        "title": "INFECTION CONTROL",
        "knowledge": seq(
            "Discuss the use of universal precautions.",
            "Describe the assessment, screening and type of Isolation required for various Infectious Disease e.g. MRSA",
            "Discuss measures to prevent needle stick injuries and verbalize reporting procedure.",
            "State at least three (3) Isolation techniques, one indication for each, as well as traffic control requirements for each.",
            "Describe the use of HEPA Filter and when to apply it (if available).",
            "Explain how to monitor the negative pressure Isolation Rooms",
            "Explain how to decontaminate Isolation equipment following an Infectious Disease in area of practice.",
            "Identify the chemical disinfectants used in the hospital.",
            "Discuss equipment storage and containment of used equipment for disposal and decontamination related to infection control.",
        ),
        "skills": seq(
            "Demonstrate hand washing technique",
            "Demonstrate use of universal precautions",
            "Demonstrate the measures to prevent needle stick injuries and reporting mechanism and document",
            "Demonstrate use of HEPA Filter and when to apply it",
            "Complete the monitoring process for negative pressure Isolation rooms",
            "Demonstrate how to decontaminate equipment used following exposure to an infectious disease",
            "Demonstrate the labeling of specimen and complete the documentation of a patient with an Infectious disease",
        ),
        "attitude": [
            ("1.", "Accept infectious patient assignment professionally and treats patient and family with dignity and respect."),
            ("2.", "Exhibit appropriate level of concern to eliminate, prevent and control the occurrence and/or exposure to infection and/or Infectious disease."),
            ("3.", "Show a belief that the environment created in the ward/ department can impact and quality of care and emotional response of a patient with an infectious disease."),
            ("4.", "Show commitment towards improving self-awareness amongst colleagues and how this helps to improve the working environment for a staff as well as patients etc."),
            ("12.", "Demonstrate ability to organize and facilitate a reflection session in and on practice after any safety issue is highlighted when caring for patients with an infection and/or infectious disease and activate findings to improve future practice and response."),
            ("13.", "Display proactivity towards safety in the work environment and minimizing the transmission of hospital acquired infectious disease for patients and staff."),
        ],
    },
    {
        "slug": "specific-admission-of-pediatric-patient",
        "title": "ADMISSION OF PEDIATRIC PATIENT",
        "knowledge": seq(
            "States the policy on admission of Pediatric patients (age limits, disease classifications, physicians to be called, and watchers.)",
            "States nurse's responsibilities on admission of pediatric patients.",
        ),
        "skills": seq(
            "Prepares room/bed for the patient and assembles necessary equipment at the bed side.",
            "Check identity band on patient.",
            "Verifies patient name and hospital admission sheet and information.",
            "Assess vital signs including weight and height.",
            "Completes the physical assessment and health history related to condition.",
            "Orients patient and attending relative to room and ward; introduces other patients and staff.",
            "Explains visiting and smoking policies, meal time isolation precautions.",
            "Explains nurse call system.",
            "Documents procedures appropriately.",
        ),
        "attitude": seq(
            "Introduces self to patient/family.",
            "Respects patient's right and responses during any procedure.",
            "Answers patiently and correctly patient questions regarding hospitalization.",
        ),
    },
    {
        "slug": "specific-anticoagulant-therapy",
        "title": "ANTICOAGULANT THERAPY",
        "knowledge": seq(
            "States the nurse's role in care of the patient receiving anti-coagulant therapy.",
            "Distinguish between anti-coagulant therapy categories 1,2 and 3.",
            "Verbalizes the potential complications for patients receiving anticoagulant therapy.",
            "Verbalizes the educational information needed by the patient receiving anticoagulant therapy.",
            "Describes the mechanism for patient follow up in the clinic.",
            "Explains the nurse's role in the use of Point of Care Testing (POCT) to obtain patient's International Normalized Ratio (INR) result.",
            "Provides and documents age specific and culturally sensitive patient teaching.",
            "States the importance of discontinuation of anticoagulant before operation.",
            "List the antidote of Heparin and Warfarin.",
        ),
        "skills": seq(
            "Demonstrates procedure for entering a patient into the anticoagulant program.",
            "Utilizes procedure for maintaining patient follow up in the clinic and participate in “call back” process as appropriate.",
            "Demonstrates POCT procedure, troubleshooting, and documentation in obtaining patient INR.",
            "Identifies patients that require immediate physician attention and performs necessary nursing interventions.",
            "Documents related assessment, interventions and care of patients receiving anticoagulants.",
            "Maintains patient's information on the anticoagulant database.",
        ),
        "attitude": seq(
            "Provides respect and maintain dignity and privacy while handling the patient/ family.",
        ),
    },
    {
        "slug": "specific-care-of-closed-chest-drainage",
        "title": "CARE OF CLOSED CHEST DRAINAGE",
        "knowledge": seq(
            "Discuss rationale chest tube insertion in are of practice.",
            "Explain the correct positioning of the patient for the insertion of a chest tube and the correct way to connect the test tube to the appropriate closed chest drainage system.",
            "Explore reasons for completing vital signs initially every 2 hours and then as needed e.g. provides baseline and can indicate recurrence of the condition that required the need for chest tube insertion.",
            "Discuss rationale for monitoring and recording amount and colour every 2 hours i.e. data for diagnosis if not known.",
            "Explain why assessment of pain at the insertion site or for chest discomfort is important e.g. interferes with adequate deep breathing and pain at insertion site particularly with inspiration may indicate improper tube placement.",
            "Explore why evaluation of the chest drainage system for fluctuation in water-seal chamber and all connection sites is important e.g. water level rises and falls with respiration until lung is expanded and persistent bubbling indicates an air leak and must be corrected.",
            "Explain the rationale for assessing insertion site and surrounding skin for presence of subcutaneous air and signs of infection/inflammation with daily dressing change is important i.e. skin integrity is altered and can led to infection and/or subcutaneous emphysema.",
            "Discuss rationale for having 2 chest drainage clamps close to closed chest drainage system at all times.",
            "Explore safe transfer procedure/s for patient with closed chest drainage system and at what height it is safe to have the closed chest drainage system.",
            "Explain how to document the chest tube site, initial chest drainage amount and color and any samples taken for investigations in the patient notes.",
        ),
        "skills": seq(
            "Prepare items and equipment required for chest tube insertion and closed chest drainage system.",
            "Demonstrate the correct positioning of the patient for the insertion of a chest tube and the correct way to connect the test tube to the appropriate closed chest drainage system.",
            "Demonstrate how to take vital signs and complete a respiratory assessment before, during and after chest tube insertion, amount of suction applied, and how to measure the amount and type of drainage.",
            "Demonstrate safety measures associated with closed chest drainage including the correct water-level requirement, and use of the 2 chest tube clamps.",
            "Complete the monitoring and recording of the amount and colour  of the chest drainage fluid and how to evaluate the chest drainage system for fluctuation in water-seal chamber and all connection sites.",
            "Explain the rationale for assessing insertion site and surrounding skin for presence of subcutaneous air and signs of infection/inflammation with daily dressing change is important i.e. skin integrity is altered and can led to infection and/or subcutaneous emphysema.",
            "Demonstrate the safe transfer procedure/s for patient with closed chest drainage system and at what height it is safe to have the closed chest drainage system.",
            "Explain how to document the chest tube site, initial chest drainage amount and color and any samples taken for investigations in the patient notes.",
            "Demonstrate the correct labelling of the samples taken and state what is required on the label and why.",
            "Perform proper technique of sharp and waste disposal.",
            "Demonstrate appropriate action when and drainage readings, color are abnormal and bubbling is persistent including the documentation of the findings and action taken.",
            "Explain how to document the chest tube site, initial drainage recording and findings, samples taken in the patient notes.",
        ),
        "attitude": seq(
            "Not to be judgmental and accepts patient response and/or refusal for the administration of BLOOD and BLOOD PRODUCTS.",
            "Ability of nurse to respond professionally and calmly if a reaction to the administration of BLOOD and/or BLOOD PRODUCTS occurs.",
            "To be self-aware of limitations in knowledge and skills and verbalize these with nurse in charge.",
            "To be approachable and open to answer patient and family's questions and ability to educate both patient and family how to keep the chest tube and drainage system safe, secure and in place.",
            "Attentive to overall patient experience e.g. pain, anxiety and have ability to provide comfort and emotional support as needed.",
            "Ability to organize and facilitate a Reflection session in and on practice after a CLOSED CHEST DRAINAGE SYSTEM learning opportunity occurs and activate findings to improve future practice and response.",
        ),
    },
    {
        "slug": "specific-neurological-deficit",
        "title": "NEUROLOGICAL DEFICIT",
        "knowledge": seq(
            "States the nurse's role in the care of the patient with neurological deficit including positioning and mobilization.",
            "Explains Glasgow Coma Scale (GCS) and indications for use.",
            "Describes additional assessments required for a patient with neurological deficit.",
            "States safety measures for a patient with neurological deficit.",
        ),
        "skills": seq(
            "Demonstrates GCS assessment and documentation.",
            "Assesses and monitors signs of neurological deficit or normal functioning including assessment of airway, swallowing, gag  reflex, speech, limb movements and strength.",
            "Demonstrates correct positioning and mobilization of a patient with neurological deficit.",
            "Documents assessments, interventions and  care of the patient with neurological deficit",
            "Provides and documents teaching to patient/family regarding the neurological deficit and associated life style changes.",
        ),
        "attitude": seq(
            "Introduces self and explain the mobilization to be  done in caring for patient with Neurologic Deficit.",
            "Demonstrates sensitivity toward individual and respect people value and cultural sensitivity.",
        ),
    },
    {
        "slug": "specific-completing-12-lead-ecg",
        "title": "COMPLETING 12 LEAD ECG",
        "knowledge": seq(
            "Explain the role and responsibilities of the nurse in completing a 12 lead ECG.",
            "Discuss the placement of V1 to V6 chest leads and limb leads.",
            "Discuss how to correctly prepare the skin for the electrode application e.g. wipe the skin with alcohol swabs and dry, shave the hair from the area and clean with alcohol swabs and dry.",
            "Explain the importance of correct patient preparation prior to a 12 Lead ECG i.e. removal of jewelry and watches.",
            "Explore the reasons that would necessitate calling the Physician to examine the patient due to a rhythm change e.g. explain the normal PQRST complex.",
            "Explain how to document the procedure in patient notes correctly.",
        ),
        "skills": seq(
            "Demonstrate the appropriate patient teaching and preparation for effective ECG results.",
            "Perform a 12 Lead ECG correctly.",
            "Demonstrate how to correctly prepare the skin for the electrode application e.g. wipe the skin with alcohol swabs and dry, shave the hair from the area and clean with alcohol swabs and dry.",
            "Demonstrate the documentation of the procedure and completes relevant patient information to identify the completed 123 Lead ECG.",
            "Demonstrate what the components of the by drawing a normal PQRST complex.",
            "Demonstrate the appropriate patient teaching and preparation for effective ECG results.",
        ),
        "attitude": seq(
            "To be self-aware of limitations in knowledge and skills and verbalize these with nurse in charge.",
            "To be approachable and open to answer patient and family' questions.",
            "Attentive to overall patient experience e.g. pain, anxiety and have ability to provide comfort and emotional support as needed.",
            "Ability to organize and facilitate a reflection session in and on practice after an administration of 12 LEAD ECG learning opportunity occurs and activates findings to improve future practice and response.",
        ),
    },
    {
        "slug": "specific-therapeutic-immobilization",
        "title": "THERAPEUTIC IMMOBILIZATION",
        "knowledge": seq(
            "States the definition of restraints and therapeutic immobilization.",
            "Verbalizes the different types of restraints.",
            "Explain the correct procedure prior to application, during the use and discontinuation of therapeutic immobilization devices.",
            "States the nurse's responsibilities in care of the patient requiring therapeutic immobilization.",
            "Verbalizes the risks for a patient requiring therapeutic immobilization.",
        ),
        "skills": seq(
            "Demonstrates application of therapeutic immobilization devices.",
            "Documents assessment, interventions and care of patient with therapeutic immobilization.",
            "Documents teaching and psychological support of the patient/ family about therapeutic immobilization.",
        ),
        "attitude": seq(
            "Maintains patient's privacy and confidentiality before and after the procedure.",
            "Answers patient and family questions politely.",
        ),
    },
    {
        "slug": "specific-oxygen-administration",
        "title": "OXYGEN ADMINISTRATION",
        "knowledge": seq(
            "Discuss methods of oxygen administration and the various doses according to area of practice.",
            "Verbalize the rationale of humidification versus the non-humidification of oxygen.",
            "State the pre, during and post patient assessment involved when administering oxygen noting for example, the use of accessory muscles, cyanosis, nasal flaring, and inability to talk in full sentences.",
            "Discuss the limitations of measuring oxygen saturation with pulse oximeter.",
            "Explore the observations and parameters for reporting significant findings and vital signs to nurse in charge and/ or physician.",
            "Discuss the need to and how to document the patient's comprehensive assessment, reassessment and vital signs of patient during the administration of oxygen and at the time of completion.",
            "Explore all the infection control issues when administering oxygen to a patient.",
        ),
        "skills": seq(
            "Demonstrate the different methods of oxygen administration and the various doses according to area of practice.",
            "Demonstrate how to set up humidification for oxygen administration.",
            "Complete the pre, during and post patient assessment involved when administering oxygen identifying, for example, the use of accessory muscles, cyanosis, nasal flaring, and inability to talk in full sentence and explore what these signs could mean.",
            "Demonstrate how to overcome the limitations of measuring oxygen saturation with pulse oximeter.",
            "Complete the observations and compare with acceptable individual parameters for reporting significant findings and vital signs to nurse in charge and/ or physician.",
            "Complete, the documentation of the patient's comprehensive assessment, re-assessment and vital signs during the administration of oxygen and at the time of completion.",
            "Demonstrate the actions required to adhere to all infection control requirements when administering oxygen to patient.",
            "Demonstrate ability to document any adverse findings and the appropriate action taken.",
            "Demonstrate accurate and correct labeling of any specimens taken during the administration of oxygen to a patient.",
        ),
        "attitude": seq(
            "Accept constructive criticism as learning opportunity/s.",
            "To be self-aware of limitations in knowledge and skills.",
            "To be approachable and open to answer patient and family's questions.",
            "Deal with and manage patient information professionally with confidentiality and integrity.",
            "Ability to organize and facilitate a reflection session in and on practice after a documentation learning opportunity occurs and activates findings to improve future practice and response.",
        ),
    },
    {
        "slug": "specific-urinary-catheterization",
        "title": "URINARY CATHETERIZATION",
        "knowledge": seq(
            "States the nursing responsibilities with regard to urinary catheter insertion.",
            "States the nursing responsibilities with regard to giving care to patient with an indwelling urinary catheter.",
            "States the educational information needed by patients who have an indwelling urinary catheter.",
        ),
        "skills": seq(
            "Demonstrates procedure for preparing patients for catheterization.",
            "Utilizes aseptic technique when indicated.",
            "Secures the urinary catheter correctly.",
            "Measures residual urine/collects urine specimen etc as needed.",
            "Utilizes age specific, culturally sensitive teaching for patients undergoing urinary catheterization.",
            "Documents assessments, intervention and care for patient with indwelling urinary catheter.",
        ),
        "attitude": seq(
            "Maintains patient's privacy and dignity.",
        ),
    },
    {
        "slug": "specific-fluid-balance",
        "title": "FLUID BALANCE",
        "knowledge": seq(
            "States criteria for measuring intake and output.",
        ),
        "skills": seq(
            "Provides culturally sensitive , age appropriate patient teaching to patient / family regarding I & O measurements.",
            "Identifies patients requiring I & O measurement",
            "Documents all fluids take in and fluids put out.",
            "Demonstrates correct fluid balance counting",
        ),
        "attitude": seq(
            "Provides respect and maintain dignity and privacy while handling the patient.",
        ),
    },
]
